# Generated by Django 2.2.1 on 2021-03-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerreg',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
