# Generated by Django 2.2.6 on 2019-11-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(max_length=20)),
                ('complaint', models.CharField(max_length=250)),
                ('disid', models.IntegerField(default=1)),
                ('cid', models.IntegerField(default=1)),
                ('sid', models.IntegerField(default=1)),
            ],
        ),
    ]
