# Generated by Django 2.2.6 on 2019-11-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='missing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('imarks', models.CharField(max_length=100)),
                ('mdate', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=250)),
                ('cid', models.IntegerField()),
            ],
        ),
    ]
