# Generated by Django 2.2.1 on 2019-12-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0006_auto_20191202_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
