# Generated by Django 2.2.1 on 2019-12-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0008_auto_20191202_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectedlawer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField()),
                ('cmpid', models.IntegerField()),
            ],
        ),
    ]
