# Generated by Django 2.2.1 on 2021-03-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0009_selectedlawer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenreg',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
