# Generated by Django 2.2.6 on 2019-11-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officername', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('contactnum', models.IntegerField()),
                ('uname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
