# Generated by Django 2.2.1 on 2019-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_officer_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='sid',
            field=models.IntegerField(default=1),
        ),
    ]
