# Generated by Django 2.2.1 on 2019-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_officer_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='dob',
            field=models.DateField(),
        ),
    ]
