# Generated by Django 2.2.1 on 2019-12-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_auto_20191205_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignmissingcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpid', models.IntegerField()),
                ('offid', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
