# Generated by Django 2.2.1 on 2019-12-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_assignmissingcase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assignmissingcase',
            new_name='assigncase',
        ),
    ]
