# Generated by Django 2.2.1 on 2019-12-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0007_assigncase_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigncase',
            old_name='remarks',
            new_name='cremarks',
        ),
    ]
