# Generated by Django 2.2.6 on 2019-11-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='disid',
        ),
    ]
